name: CI
on:
  push:
    branches:
      - master
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install deps
        run: forge install
      
      - name: Build Rave
        run: forge build

      - name: Check gas snapshots
        run: forge snapshot --check

      - name: Run tests
        run: |
          forge test --ffi --match-contract Rave512BitFuzzTester
          forge test --ffi --match-contract Rave1024BitFuzzTester
          forge test --ffi --match-contract Rave2048BitFuzzTester
          forge test --ffi --match-contract Rave3072BitFuzzTester
          forge test --ffi --match-contract Rave4096BitFuzzTester
