name: CI
on:
  push:
    branches:
      - master
      - json
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install deps
        run: forge install
                
      - name: Remappings
        run: forge remappings
      
      - name: Build Rave
        run: forge build


      # - name: Check gas snapshots
      #   run: forge snapshot --check --ffi

      - name: Run tests
        run: |
          forge test --ffi --match-contract TestBase64 -vvvv
          forge test --ffi --match-contract TestJSONBuilder -vvvv
          forge test --ffi --match-contract TestBasicJson -vvvv
          forge test --ffi --match-contract TestRemoteAttestationEvidenceJson -vvvv
          forge test --ffi --match-contract TestRSA -vvvv
          forge test --ffi --match-contract TestIntelCert -vvvv
          forge test --ffi --match-contract Test512BitCertChain -vvvv
          forge test --ffi --match-contract Test1024BitCertChain -vvvv
          forge test --ffi --match-contract Test2048BitCertChain -vvvv
          forge test --ffi --match-contract Test3072BitCertChain -vvvv
          forge test --ffi --match-contract Test4096BitCertChain -vvvv
          forge test --ffi --match-contract RaveInstanceTest -vvvv
          forge test --ffi --match-contract RaveSanityTester -vvvv
          forge test --ffi --match-contract RaveFuzzTester -vvvv
